/**
 * Digital Waybill PDF generation - Shipco branding, tracking QR, merchant & receiver details, weight.
 * Uses jspdf + qrcode. Run on server only.
 */

import { jsPDF } from "jspdf";
import QRCode from "qrcode";

export interface WaybillData {
  trackingId: string;
  merchantName: string;
  merchantEmail: string;
  merchantAddress: string;
  receiverName: string;
  receiverPhone: string;
  receiverAddress: string;
  packageWeightKg: number;
  cost: number;
  trackUrl: string;
  /** Optional: for external 3PL partners (DHL, GIG, FedEx) - shows "Track via Partner" link */
  partnerName?: string;
  partnerTrackingUrl?: string;
}

/** Generate PDF buffer for Digital Waybill */
export async function generateWaybillPdf(data: WaybillData): Promise<Buffer> {
  const doc = new jsPDF({ format: "a4", unit: "mm" });
  const pageHeight = (doc as unknown as { internal: { pageSize: { getHeight: () => number } } }).internal.pageSize.getHeight();
  let y = 20;

  // - Shipco Branding -
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(27, 55, 100); // deep logistics blue
  doc.text("Shipco LOGISTICS", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Digital Waybill", 20, y);
  y += 14;

  // - Tracking + QR (mocked QR points to track URL) -
  doc.setDrawColor(200, 200, 200);
  doc.rect(20, y, 50, 50);
  try {
    const qrDataUrl = await QRCode.toDataURL(data.trackUrl, { width: 180, margin: 0 });
    const qrImg = qrDataUrl.replace(/^data:image\/\w+;base64,/, "");
    doc.addImage(qrImg, "PNG", 22, y + 2, 46, 46);
  } catch {
    doc.setFontSize(8);
    doc.text("QR", 42, y + 26);
  }
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Tracking ID", 78, y + 12);
  doc.setFont("helvetica", "normal");
  doc.text(data.trackingId, 78, y + 20);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Track: " + data.trackUrl, 78, y + 28);
  y += 58;

  // - Merchant Details -
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Merchant / Sender", 20, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(data.merchantName, 20, y);
  y += 5;
  doc.text(data.merchantEmail, 20, y);
  y += 5;
  doc.text(data.merchantAddress, 20, y);
  y += 12;

  // - Receiver Details -
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Receiver", 20, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(data.receiverName, 20, y);
  y += 5;
  doc.text(data.receiverPhone, 20, y);
  y += 5;
  doc.text(data.receiverAddress, 20, y);
  y += 14;

  // - Weight & Cost -
  doc.setFont("helvetica", "bold");
  doc.text("Weight (kg)", 20, y);
  doc.text("Cost (NGN)", 80, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(String(data.packageWeightKg), 20, y);
  doc.text(new Intl.NumberFormat("en-NG").format(data.cost), 80, y);
  y += 10;

  // - Track via Partner (external 3PL) -
  if (data.partnerName && data.partnerTrackingUrl) {
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(244, 0, 9); // #F40009
    doc.text(`Track via ${data.partnerName}:`, 20, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(59, 130, 246); // blue link
    doc.text(data.partnerTrackingUrl, 20, y + 5);
    y += 14;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by Shipco Logistics. This is a digital waybill.", 20, pageHeight - 20);

  return Buffer.from(doc.output("arraybuffer"));
}
